kind: Secret
apiVersion: {{ secret.api_version }} 
metadata:
  name: "{{ secret.name }}"
  namespace: "{{ meta.namespace }}"
  labels:
    app: "{{ name }}"
    cr: "{{ meta.name }}"
    operator: "{{ kind }}"
    action: main
stringData: 
  {{ secret.redis_password_field }}: "{{ default_user_password }}"
{% if replicas > 1 %}
  {{ secret.sentinel_password_field }}: "{{ sentinel.password }}"
{% endif %}
